-- ========================================
-- CAMBIAR GENERATED ALWAYS → GENERATED BY DEFAULT
-- (para que la app pueda hacer upsert con IDs explícitos)
-- ========================================

ALTER TABLE empresa ALTER COLUMN id_empresa SET GENERATED BY DEFAULT;
ALTER TABLE vehiculo ALTER COLUMN id_vehiculo SET GENERATED BY DEFAULT;
ALTER TABLE conductor ALTER COLUMN id_conductor SET GENERATED BY DEFAULT;
ALTER TABLE ruta ALTER COLUMN id_ruta SET GENERATED BY DEFAULT;
ALTER TABLE monitoreo ALTER COLUMN id_monitoreo SET GENERATED BY DEFAULT;
ALTER TABLE consumo_combustible ALTER COLUMN id_consumo SET GENERATED BY DEFAULT;
ALTER TABLE incidencia ALTER COLUMN id_incidencia SET GENERATED BY DEFAULT;
ALTER TABLE mantenimiento ALTER COLUMN id_mantenimiento SET GENERATED BY DEFAULT;
